language: node_js

node_js:
  - "stable"

services:
  - postgresql

cache:
  directories:
    - "node_modules"

before_script:
  - psql -c 'create database shoplink;' -U postgres
  - npm i nyc --save-dev
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - nyc --reporter=lcov --reporter=text-lcov npm test
  - npm run coveralls

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_fail: npm run coverage

notifications:
  slack: andela:LX8VPRMaSP4tskr94puPVmFf

